### ISSUE TITLE
webcam feature?

### ISSUE THREAD

**Issue by eyallampel1** [hkociemba/RubiksCube-TwophaseSolver#1]
do you work on a webcam (RPI Camera) feature similar to cube explorer ?

**Comment by hkociemba** [comment]
I played around with opencv a bit but there is yet nothing which would be worth to show. But indeed I will try to add such a feature.

**Comment by hkociemba** [comment]
The computer vision part with opencv is implemented now and works really good (at least with my webcam).

**Comment by jobosch** [comment]
Which version for python and opencv do you use?
