### ISSUE TITLE
Cam is not working correctly

### ISSUE THREAD

**Issue by jobosch** [hkociemba/RubiksCube-TwophaseSolver#12]
Hi, I have a mac and the webcam does not work correctly. I think it's because of the version of python or opencv. If someone could tell me in which verisons it works I would be grateful.

**Comment by hkociemba** [comment]
As written in the description you should use Python 3.4 or higher and you have the numpy package installed. 
As written in vision2.py line 262:
 works for OpenCV 3.2 or higher. For versions < 3.2 omit im2 

More details about what is going wrong should be given. That the "webcam does not work correctly" does not allow me to track down the problem.
