### ISSUE TITLE
Tables to sub-folder?

### ISSUE THREAD

**Issue by manganite** [hkociemba/RubiksCube-TwophaseSolver#14]
Hi, I want to use your solver for an app. Everything works fine so far. I just have a request of a more cosmetic nature. Is there any simple solution to move all the table files away from the root folder of my app and hide them in some sub-folder?

**Comment by hkociemba** [comment]
No, you will have to dig into the source code and change the routines where files are written. I think all of these contain a variable "fname".

**Comment by manganite** [comment]
Ok, I see. Nevertheless, thanks for your reply.

**Comment by zhang-zk21t** [comment]
It helps to modify the macro `FOLDER` in `defs.py`.
