### ISSUE TITLE
Tables files

### ISSUE THREAD

**Issue by Pasqui03** [hkociemba/RubiksCube-TwophaseSolver#16]
This is not issue, just a question.
The files generated on first run this program. What are these files? And why we need these file?

**Comment by hkociemba** [comment]
In phase 1 and also in phase 2 the positions are represented by a point P in a 3 dimensional coordinate space. A move - for example R2 - then transfers P to another point  P' and there are tables which encode these transisions of coordinates. The big tables are the pruning tables which give us an lower bound for each point P how many moves it takes at least to solve the phase 1 or phase 2. The solved position has coordinates (0,0,0). There are also tables which encode the transformation of a point P when applying one of the 48 cube symmetries etc. Take a look at my homepage for more details.
