### ISSUE TITLE
example.py will not find correct solution when connected with server

### ISSUE THREAD

**Issue by meridsa** [hkociemba/RubiksCube-TwophaseSolver#4]
After entering the cube map into the solver client it will connect with the server but will not output the solution in difference to the readme image. See attached image. I am running it on Mac as seen, in python3.6.

![solverclient_not_responding](https://user-images.githubusercontent.com/35993351/38554453-fcab2c38-3cc2-11e8-9dc1-3e5a867eb89c.png)

All the best,
Mons

**Comment by meridsa** [comment]
However the client works from a web browser. Accessing 127.0.0.1:8080/[STATE_STRING] will provide solution move-set.

**Comment by hkociemba** [comment]
Did you try it on different machines? Is it a general problem?

**Comment by meridsa** [comment]
Hi! I finally put it on a raspberry pi model 3 and it worked really well there.
