### ISSUE TITLE
from enum import IntEnum

### ISSUE THREAD

**Issue by agostini81** [hkociemba/RubiksCube-TwophaseSolver#5]
Hello there 
I cant run this program , the file class enum.py is missing 
this is being imported from enums.py 
 from enums import IntEnum

it doesn't run , do you have the type of IntEnum ? or the class ? so I can run it

**Comment by hkociemba** [comment]
enum is part of Python since version 3.4
https://docs.python.org/3/library/enum.html
Please check the version you use.
