### ISSUE TITLE
Solver fails to solve certain states

### ISSUE THREAD

**Issue by LRFLEW** [hkociemba/RubiksCube-TwophaseSolver#7]
This solver fails to correctly solve the following state: `UUUUUUUUURRRRRLRRRFFFFFBFFFDDDDDDDDDLLLLLRLLLBBBFBBBBB`. The server simply responds with the empty solution string `(0f)` as if it were the solved state (which it isn't). 

Some isomorphic states also produce this problem. Curiously, however, this doesn't appear to affect all isomorphic states. In particular, if I give it the isomorphic state `UUUUUUUDURRRRRRRRRFFFFFFFBFDDDDDDDUDLLLLLLLLLBBBBBBBFB`, then it's able to produce an 8f solution (`R2 F2 R2 U2 L2 B2 L2 U2`). Best I can tell, the bug occurs on all isomorphic states that keep the up and down slices solved.

**Comment by LRFLEW** [comment]
Update: I found another state that results in this issue. `UUUUUUUUURRRLRLRRRFFFFFFFFFDDDDDDDDDLLLRLRLLLBBBBBBBBB`. I tested all the isomorphic states, and the only one that also fails is `UUUUUUUUURRRRRRRRRFFFBFBFFFDDDDDDDDDLLLLLLLLLBBBFBFBBB`. This is more evidence of my theory that it occurs when the up and down slices are solved, but the middle slice isn't.

**Comment by LRFLEW** [comment]
Found where the problem occurs in the code, and it occurs when, at the start of Phase 2, the up and down layers are solved. At line 139 of solver.py, `dist` is computed using `corners` and `ud_edges`, but not with `slice_sorted`. When the up and down layers are solved, then `dist` is set to `0`, even if the middle layer isn't solved. This means that the first call to `search_phase2` has `togo_phase2 = 0`, which means it considers the state solved.

Testing it, setting `dist=max(dist, 1)` results in a valid solution to the given cases, but results in a non-zero length solution to the solved cube. Doing this conditionally when `slice_sorted > 0` prevents that issue. Ideally, the function `CoordCube.get_depth_phase2` should be updated to account for `slice_sorted` (which I don't understand the heuristic well enough to do myself). Below is the patch I came up with, but I don't think is ideal.

```
diff --git a/solver.py b/solver.py
index 78540ba..208d564 100644
--- a/solver.py
+++ b/solver.py
@@ -137,6 +137,8 @@ class SolverThread(thr.Thread):
             ud_edges = coord.u_edges_plus_d_edges_to_ud_edges[24 * u_edges + d_edges % 24]
 
             dist2 = self.co_cube.get_depth_phase2(corners, ud_edges)
+            if dist2 == 0 and slice_sorted != 0:
+                dist2 = 1
             for togo2 in range(dist2, togo2_limit):  # do not use more than togo2_limit - 1 moves in phase 2
                 self.sofar_phase2 = []
                 self.search_phase2(corners, ud_edges, slice_sorted, dist2, togo2)
```

**Comment by hkociemba** [comment]
You analyzed the code correctly. Thanks for your notification. The easiest fix is 

 if togo_phase2 == 0 and slice_sorted == 0:
instead of

 if togo_phase2 == 0
in line 56 of solver.py
